### PR TITLE
Move FreeBSD CI to Cirrus

### PR DESCRIPTION
**Pull request by giordano**
I'm missing how to setup Cirrus for the repository/organisation.  CC: @ararslan

### CODE REVIEW

**Comment by ararslan** [comment]
Cirrus was like half-installed for this organization; I just had to edit the installation from the GitHub Marketplace to tell it whether it's allowed to access all repos or just selected ones. Should be all set now.

As an aside, we could also run CI on platforms like ARM and Alpine with Cirrus ["soon"](https://github.com/ararslan/CirrusCI.jl/pulls/13).

**Comment by giordano** [comment]
Ok, I can hold off this PR until we can move also away from Drone.  Thanks!

**Comment by ararslan** [comment]
I'd recommend just going ahead with this PR and adding other platforms on Cirrus once I have it nailed down. The green status checks in my PR I linked are a bit misleading as CI for that repo doesn't cover the mechanism by which other repos install CirrusCI.jl. (`sh -c "$(fetch ...)"` works fine for FreeBSD but `fetch` is FreeBSD-specific and I don't want people to have to separate out the installation step into a matrix just so they can install `curl` or whatever a bunch of different ways. If you have thoughts or ideas on that front, feel free to comment on that PR!)

**Comment by giordano** [comment]
Cirrus still doesn't start here.

**Comment by ararslan** [comment]
Maybe because it's in draft mode?

**Comment by ararslan** [comment]
wtf, https://cirrus-ci.com/github/JuliaPackaging only shows BinaryProvider.

**Comment by ararslan** [comment]
I changed the org settings for Cirrus from access to all repos to only this one, no idea whether that will do anything

**Comment by giordano** [comment]
Sounds like I had to push a new commit, I guess it doesn't rebuild on a new merge commit?

**Comment by ararslan** [comment]
Huh, I guess not, weird. I wonder if that's configurable.

**Review by ararslan — APPROVED** [review]

**Pull request merged**
