### PR TITLE
Add minimal infrastructure for testing

### PR DESCRIPTION
**Pull request by giordano**
It's now that [`JLLTools.jl`](https://github.com/JuliaPackaging/JLLTools.jl) would be very useful: I'd like to automatically generate the wrappers during the tests, but the only place where the code currently lives is in BinaryBuilder.  For the time being I went with locally generating the wrappers and then we'll figure out what to do.  This isn't ideal, but at least I setup a minimal testing framework and caught the first bug (`PATH` and `LIBPATH` were undefined, added to `src/toplevel_generators.jl`)

### CODE REVIEW

**Comment by giordano** [comment]
Right, this depends on https://github.com/JuliaRegistries/General/pull/21327

**Comment by giordano** [comment]
So, apparently `HelloWorldC` isn't available for macOS with Julia nightly: https://travis-ci.com/github/JuliaPackaging/JLLWrappers.jl/jobs/384427080#L205 :confused:  @staticfloat can you please confirm that's the case?

**Comment by staticfloat** [comment]
Ah, okay, so the issue here is that since I added `os_version` support to Platforms, it will generate a triplet of `x86_64-apple-darwin` for a MacOS object with no `os_version`.  Here, we have an `Artifacts.toml` that doesn't define an `os_version` mapping for the MacOS artifact, but then the wrapper is named `x86_64-apple-darwin14`.

You either need to add a `os_version=14` mapping to the Artifacts.toml, or rename the wrapper to `x86_64-apple-darwin.jl`.

**Comment by staticfloat** [comment]
This should get fixed in BB as well; we are probably naming something incorrectly somewhere if we're still getting the `14`.

**Comment by staticfloat** [comment]
I've changed the triplet parsing here to use `parse()` -> `select_platform()` so that if we generate things with a BB version that doesn't spit out triplets in _exactly_ the same way as we expect, as long as we can parse the name, we're still okay.

**Pull request merged**
